### ISSUE TITLE
Ressource "nxos_ipv4_static_route" import forces replacement

### ISSUE THREAD

**Issue by Pidpad** [CiscoDevNet/terraform-provider-nxos#305]
Hey guys, I try to manage my nxos (non fabric/aci) switches via terraform and ran into the following issue.
When I try to import my existing static ipv4 routes, terraform wants to replace these routes instead of importing them.

Is there any way to import my existing routes without terraform recreating those?

switch model: N9K-C93360YC-FX2
nxos version: 10.2(5)

my research so far

visore.html page on the switch, to view the dn information on the switch.
I guess the switch is not providing more information on the api call? Maybe a switch update could fix this?

![Image](https://github.com/user-attachments/assets/2ee38791-abc6-48aa-8080-24f994f92ee5)

Terraform plan output:

```terraform
  # module.vlan["VLAN"].nxos_ipv4_static_route.static_route["switchname"] must be replaced
  # (imported from "sys/ipv4/inst/dom-/rt-[cidr/24]")
  # Warning: this will destroy the imported resource
-/+ resource "nxos_ipv4_static_route" "static_route" {
      + device    = "switchname"
      ~ id        = "sys/ipv4/inst/dom-[default]/rt-[cidr/24]" -> (known after apply)
      + next_hops = [
          + {
              + address      = "nexthop" # forces replacement
              + description  = "terraform.mananged"
              + interface_id = "unspecified" # forces replacement
              + object       = 10
              + preference   = 123
              + tag          = 10
              + vrf_name     = "default" # forces replacement
            },
        ]
      ~ prefix    = "" -> "cidr/24" # forces replacement
      + vrf_name  = "default" # forces replacement
    }
```

The route in the show run on the switch looks like this:

ip route cidr/24 nexthop name terraform.mananged

**Comment by Pidpad** [comment]
My terraform code looks like this

```
resource "nxos_ipv4_static_route" "static_route" {
  device       = "switchname"
  vrf_name = "default"
  prefix   = "cidr/24"
  next_hops = [
    {
    interface_id = "unspecified"
    address      = "nexthop"
    vrf_name     = "default"
    description  = "terraform.mananged"
    object       = 10
    preference   = 123
    tag          = 10
  }
  ]
}
```

As I use a custom variable for my switches and use a for_each I thought I should try a simple test against the DevNet AlwaysOn Sandbox and got this results

```terraform

terraform {
  required_version = ">= 1.1.0"

  required_providers {
    nxos = {
      source  = "CiscoDevNet/nxos"
      version = "0.5.7"
    }
  }
}

provider "nxos" {
  alias    = "nxos"
  username = "Username"
  password = "Password"
  url      = "https://sbx-nxos-mgmt.cisco.com"
}

#STATIC ROUTE TEST
import {
    to = nxos_ipv4_static_route.static_route
    id = "sys/ipv4/inst/dom-[management]/rt-[0.0.0.0/0]"
}

#STATIC ROUTE TEST
resource "nxos_ipv4_static_route" "static_route" {
  provider             = nxos.nxos
  vrf_name = "management"
  prefix   = "0.0.0.0/0"
  next_hops = [
    {
    interface_id = "unspecified"
    address      = "10.10.20.254/32"
    vrf_name     = "management"
    object       = 0
    preference   = 0
    tag          = 0
  }
  ]
}
```

TF still wants to replace the route
```
❯ tf plan
nxos_ipv4_static_route.static_route: Preparing import... [id=sys/ipv4/inst/dom-[management]/rt-[0.0.0.0/0]]
nxos_ipv4_static_route.static_route: Refreshing state... [id=sys/ipv4/inst/dom-[management]/rt-[0.0.0.0/0]]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # nxos_ipv4_static_route.static_route must be replaced
  # (imported from "sys/ipv4/inst/dom-[management]/rt-[0.0.0.0/0]")
  # Warning: this will destroy the imported resource
-/+ resource "nxos_ipv4_static_route" "static_route" {
      ~ id        = "sys/ipv4/inst/dom-[management]/rt-[0.0.0.0/0]" -> (known after apply)
        next_hops = [
            {
                address      = "10.10.20.254/32"
                description  = null
                interface_id = "unspecified"
                object       = 0
                preference   = 0
                tag          = 0
                vrf_name     = "management"
            },
        ]
        prefix    = "0.0.0.0/0"
      + vrf_name  = "management" # forces replacement
    }

Plan: 1 to import, 1 to add, 0 to change, 1 to destroy.
```

show run on the devnet sandbox
```
nxos# show ip route 0.0.0.0/0 vrf management
IP Route Table for VRF "management"
'*' denotes best ucast next-hop
'**' denotes best mcast next-hop
'[x/y]' denotes [preference/metric]
'%<string>' in via output denotes VRF <string>

0.0.0.0/0, ubest/mbest: 1/0
    *via 10.10.20.254, [1/0], 5d17h, static
```

**Comment by danischm** [comment]
This should be fixed in v0.5.8.

**Comment by Pidpad** [comment]
Thanks for the quick fix @danischm!
I have a similar problem during importing a port-channel interface with a for_each.

Without a for_each on the devnet sandbox, I can import the port-channel interface without a replacement. When I try to do it in my enviroment, it wants to replace the interface_id. Looks like a similar problem. Can I post more information in this issue or should I create a new one?

**Comment by danischm** [comment]
I would suggest creating a new one.

**Comment by Pidpad** [comment]
I just tested it with the version 0.58 and the replacement for the "vrf_name" is fixed.
But I still get "forces replacement" in the "next_hops" part. Could this be related to the switch not providing the information as seen in my first image?

```terraform
  # module.vlan["VLANXYZ"].nxos_ipv4_static_route.static_route["SW-01"] must be replaced
  # (imported from "sys/ipv4/inst/dom-/rt-[cidr/24]")
  # Warning: this will destroy the imported resource
-/+ resource "nxos_ipv4_static_route" "static_route" {
      + device    = "SW-01"
      ~ id        = "sys/ipv4/inst/dom-[default]/rt-[cidr/24]" -> (known after apply)
      + next_hops = [
          + {
              + address      = "1.1.1.1" # forces replacement
              + description  = "TF Test"
              + interface_id = "unspecified" # forces replacement
              + object       = 10
              + preference   = 123
              + tag          = 10
              + vrf_name     = "default" # forces replacement
            },
        ]
        prefix    = "cidr/24"
        vrf_name  = "default"
    } 
´´´

**Comment by danischm** [comment]
Can you share the resource definition and existing configuration you are using?

**Comment by Pidpad** [comment]
sure, but I think most of it is already in my first post.

Switch Config
```
SW-01# show run | inc 192.168.0.0/24
ip route 192.168.0.0/24 10.0.0.1 name TF_TEST
```

Switch show command
```
SW-01# show ip route 192.168.0.0/24 detail
IP Route Table for VRF "default"
'*' denotes best ucast next-hop
'**' denotes best mcast next-hop
'[x/y]' denotes [preference/metric]
'%<string>' in via output denotes VRF <string>

192.168.0.0/24, ubest/mbest: 1/0
    *via 10.0.0.1, [1/0], 4w1d, static
         recursive next hop: 172.31.255.247/32
     via 10.1.0.1, Eth1/94, [110/40], 2d14h, ospf-1, type-1, tag 401
```

Terraform Resource
```terraform
import {
    to = module.vlan["VLANXYZ"].nxos_ipv4_static_route.static_route["SW-01"]
    id = "sys/ipv4/inst/dom-[default]/rt-[192.168.0.0/24]"
}

resource "nxos_ipv4_static_route" "static_route" {
  for_each   = toset([for switch in var.switches : switch.name if (switch.static_routes && var.layer3_vlan)])
  device       = each.key
  vrf_name = "default"
  prefix   = var.subnet
  next_hops = [
    {
    interface_id = "unspecified"
    address      = "10.0.0.1"
    vrf_name     = "default"
    description  = "${var.vlan_name}"
    object       = 10
    preference   = 123
    tag          = 10
  }
  ]
}
```

Terraform Output
```terraform
  # module.vlan["VLANXYZ"].nxos_ipv4_static_route.static_route["SW-01"] must be replaced
  # (imported from "sys/ipv4/inst/dom-/rt-[192.168.0.0/24]")
  # Warning: this will destroy the imported resource
-/+ resource "nxos_ipv4_static_route" "static_route" {
      + device    = "SW-01"
      ~ id        = "sys/ipv4/inst/dom-[default]/rt-[192.168.0.0/24]" -> (known after apply)
      + next_hops = [
          + {
              + address      = "10.0.0.1" # forces replacement
              + description  = "TF_TEST"
              + interface_id = "unspecified" # forces replacement
              + object       = 10
              + preference   = 123
              + tag          = 10
              + vrf_name     = "default" # forces replacement
            },
        ]
        prefix    = "192.168.0.0/24"
        vrf_name  = "default"
    }
```

**Comment by danischm** [comment]
I have configured this:

```
ip route 192.168.0.0/24 10.0.0.1 name TF_TEST
```

..and then used the following TF config:

```hcl
provider "nxos" {
  devices = [{
    name = "SW-01"
    url = "https://x.x.x.x"
  }]
}

import {
    to = nxos_ipv4_static_route.static_route["SW-01"]
    id = "sys/ipv4/inst/dom-[default]/rt-[192.168.0.0/24]"
}

resource "nxos_ipv4_static_route" "static_route" {
  for_each   = toset(["SW-01"])
  device       = each.key
  vrf_name = "default"
  prefix   = "192.168.0.0/24"
  next_hops = [
    {
    interface_id = "unspecified"
    address      = "10.0.0.1/32"
    vrf_name     = "default"
    object       = 0
    preference   = 0
    tag          = 0
  }
  ]
}
```

which works, except the device name, which can currently not be provided:

```
Terraform will perform the following actions:

  # nxos_ipv4_static_route.static_route["SW-01"] will be updated in-place
  # (imported from "sys/ipv4/inst/dom-/rt-[192.168.0.0/24]")
  ~ resource "nxos_ipv4_static_route" "static_route" {
      + device    = "SW-01"
        id        = "sys/ipv4/inst/dom-[default]/rt-[192.168.0.0/24]"
        next_hops = [
            {
                address      = "10.0.0.1/32"
                description  = null
                interface_id = "unspecified"
                object       = 0
                preference   = 0
                tag          = 0
                vrf_name     = "default"
            },
        ]
        prefix    = "192.168.0.0/24"
        vrf_name  = "default"
    }

Plan: 1 to import, 0 to add, 1 to change, 0 to destroy.
```

**Comment by simon-wessel** [comment]
We still observe this and the weird occurrences with increased list sizes makes me assume that this could be a provider bug.

@danischm Would it be possible to reopen this ticket?

**Comment by Pidpad** [comment]
I took a call with @simon-wessel  and I think we could locate the issue. It's not even an issue with the import, but with the "devices" variable in the provider or with the parsing of that variable.

main.tf

```terraform
terraform {
  required_version = ">= 1.1.0"

  required_providers {
    nxos = {
      source  = "CiscoDevNet/nxos"
      version = "0.5.10"
    }
  }
}

locals {
  switches = {
    SW-01 = {
      name = "SW-01"
      url  = "https://SW-01:8443"
      foo  = false
    }
    SW-02 = {
      name = "SW-02"
      url  = "https://SW-02:8443"
      foo  = true
    }
  }
}

provider "nxos" {
  username = var.switch_username
  password = var.switch_password
  devices  = toset([for switch in local.switches : switch])
}
data "nxos_ipv4_static_route" "SW-01" {
  vrf_name = "default"
  prefix   = "192.168.0.0/24"
}

output "datasource_static_route" {
  value = data.nxos_ipv4_static_route.SW-01
}
```

Output
```terraform
data.nxos_ipv4_static_route.SW-01: Reading...
data.nxos_ipv4_static_route.SW-01: Read complete after 0s [id=sys/ipv4/inst/dom-[default]/rt-[]]

Changes to Outputs:
  + datasource_static_route = {
      + device    = null
      + id        = "sys/ipv4/inst/dom-[default]/rt-[]"
      + next_hops = null
      + prefix    = ""
      + vrf_name  = "default"
    }
```

If you change the variable "foo" on both switches to true, it works.

```terraform
locals {
  switches = {
    SW-01 = {
      name = "SW-01"
      url  = "https://SW-01:8443"
      foo  = true
    }
    SW-02 = {
      name = "SW-02"
      url  = "https://SW-02:8443"
      foo  = true
    }
  }
}
```

Output
```terraform
data.nxos_ipv4_static_route.SW-01: Reading...
data.nxos_ipv4_static_route.SW-01: Read complete after 0s [id=sys/ipv4/inst/dom-[default]/rt-[192.168.0.0/24]]

Changes to Outputs:
  + datasource_static_route = {
      + device    = null
      + id        = "sys/ipv4/inst/dom-[default]/rt-[192.168.0.0/24]"
      + next_hops = [
          + {
              + address      = "10.0.0.1/32"
              + description  = ""
              + interface_id = "unspecified"
              + object       = 0
              + preference   = 0
              + tag          = 0
              + vrf_name     = "default"
            },
        ]
      + prefix    = "192.168.0.0/24"
      + vrf_name  = "default
```

It also works if one is "false" and one is "true" and you use the `devices = toset([for switch in var.switches : {name = switch.name, url = switch.url}])` instead of `devices  = toset([for switch in local.switches : switch])`

```terraform
locals {
  switches = {
    SW-01 = {
      name = "SW-01"
      url  = "https://SW-01:8443"
      foo  = false
    }
    SW-02 = {
      name = "SW-02"
      url  = "https://SW-02:8443"
      foo  = true
    }
  }
}

provider "nxos" {
  username = var.switch_username
  password = var.switch_password
  #devices  = toset([for switch in local.switches : switch])
  devices = toset([for switch in local.switches : {name = switch.name, url = switch.url}])
}
```
Output is the same as if both foo variables are true

```terraform
data.nxos_ipv4_static_route.SW-01: Reading...
data.nxos_ipv4_static_route.SW-01: Read complete after 0s [id=sys/ipv4/inst/dom-[default]/rt-[192.168.0.0/24]]

Changes to Outputs:
  + datasource_static_route = {
      + device    = null
      + id        = "sys/ipv4/inst/dom-[default]/rt-[192.168.0.0/24]"
      + next_hops = [
          + {
              + address      = "10.0.0.1/32"
              + description  = ""
              + interface_id = "unspecified"
              + object       = 0
              + preference   = 0
              + tag          = 0
              + vrf_name     = "default"
            },
        ]
      + prefix    = "192.168.0.0/24"
      + vrf_name  = "default
```

I hope this helps fixing the issue. Thanks to @simon-wessel , I have a workaround with `devices = toset([for switch in local.switches : {name = switch.name, url = switch.url}])` and can continue with my task.

**Comment by danischm** [comment]
The provider has been completely refactored and now supports various methods of importing with one or more devices. If something is not working as expected, please let us know.
